### ISSUE TITLE
Can it be based on a stable version?

### ISSUE THREAD

**Issue by pexcn** [JiaY-shi/openwrt#14]
### Describe the bug

Not a bug. Just want to ask, can it be based on the stable version of openwrt 23.05?

### OpenWrt version

openwrt 23.05

### OpenWrt target/subtarget

ipq60xx

### Device

xiaomi ax1800

### Image kind

Self-built image

### Terms

- [X] I am reporting an issue for OpenWrt, not an unsupported fork.

**Comment by JiaY-shi** [comment]
No, the ipq60xx series is based on openwrt main and kernel 6.1, but the kernel of openwrt 23.05 is 5.15.

**Comment by pexcn** [comment]
OK, by the way, what is the difference between `ipq60xx-devel_nss` and `ipq60xx-devel` branches? which one is recommended?

**Comment by pexcn** [comment]
Can we add support for more devices, such as Xiaomi AX1800 and ZN-M2?

**Comment by JiaY-shi** [comment]
> OK, by the way, what is the difference between `ipq60xx-devel_nss` and `ipq60xx-devel` branches? which one is recommended?

@pexcn The ipq60xx-devel_nss branch has full nss core support, but is only experimental. The ipq60xx-devel branch is relatively stable and is recommended.

**Comment by JiaY-shi** [comment]
> Can we add support for more devices, such as Xiaomi AX1800/Redmi AX5 and ZN-M2?

@pexcn Sorry, I don't have these devices, so I can't provide support.

**Comment by pexcn** [comment]
OK, I found the dts for xiaomi ax1800 in [another repo](https://github.com/coolsnowwolf/openwrt-gl-ax1800/commit/0fc6174e6646d81b4c42906c3f9400b17847f9ff#diff-aae42cca33f28028fa4e6b6759c62ab7f8b8fbb88f555a51c7df73647e6bde0a), maybe I can try it. 😁

**Comment by JiaY-shi** [comment]
@pexcn Hello guys, how is the porting of these devices for Xiaomi AX1800/Redmi AX5 and ZN-M2? I plan to buy a ZN-M2.

**Comment by pexcn** [comment]
> @pexcn Hello buddy, how is the porting of these devices for Xiaomi AX1800/Redmi AX5 and ZN-M2? I plan to buy a ZN-M2.

Hi, it hasn't started yet, I'm planning to give it a try this weekend.😅
At the same time, I have just cherry-picked some necessary commits and plan to [make a version for myself](https://github.com/openwrt-dev/openwrt-ipq60xx/commits/main), thank you very much for your commits~

By the way, ZN-M2 PCB is very fragile and easy to break, and its WiFi signal is poor, so not recommended to buy.
In my DIY process, I only succeeded with my second purchase.

At the same time, it is highly recommended that you buy Xiaomi AX1800 (It should be very cheap now on the second-hand market, the price is estimated to be about twice that of ZN-M2), It has good appearance, heat dissipation, and a very good quality PCB. Still, I don't know why this model is so unpopular.

**Comment by pexcn** [comment]
@JiaY-shi I found the patch for ZN-M2 [here](https://github.com/kiddin9/OpenWrt_x86-r2s-r4s-r5s-N1/blob/master/devices/qualcommax_ipq60xx/patches/v6m2.patch), it should work directly, but I haven't tried it yet.

**Comment by JiaY-shi** [comment]
> > @pexcn Hello buddy, how is the porting of these devices for Xiaomi AX1800/Redmi AX5 and ZN-M2? I plan to buy a ZN-M2.
> 
> Hi, it hasn't started yet, I'm planning to give it a try this weekend.😅 At the same time, I have just cherry-picked some necessary commits and plan to [make a version for myself](https://github.com/openwrt-dev/openwrt-ipq60xx/commits/main), thank you very much for your commits~
> 
> By the way, ZN-M2 PCB is very fragile and easy to break, and its WiFi signal is poor, so not recommended to buy. In my DIY process, I only succeeded with my second purchase.
> 
> At the same time, it is highly recommended that you buy Xiaomi AX1800 (It should be very cheap now on the second-hand market, the price is estimated to be about twice that of ZN-M2), It has good appearance, heat dissipation, and a very good quality PCB. Still, I don't know why this model is so unpopular.

@pexcn Thanks for your sharing and suggestions, I will reconsider Xiaomi AX1800 and ZN-M2. You are also welcome to share your use of the source code of this warehouse for these two devices.

**Comment by pexcn** [comment]
@JiaY-shi For this repo I haven't tried yet, but I have some experience with openwrt [19.07](https://github.com/openwrt-dev/openwrt-ipq60xx/commits/openwrt-19.07) version (kernel 4.4.60).

For this version, except that the kernel version is too low and batman-adv cannot compile with the V protocol, everything else works well.
For ZN-M2, everything works well, but after turning on wireless, the SoC temperature is 10 degrees higher than that of disabled wireless, maybe it's because ZN-M2 doesn’t radiating well.
For Xiaomi AX1800, everything works fine except wireless. It's wireless signal is extremely low, I think this firmware caused by the lack of `board-2.bin` for this model, but how to obtain `board-2.bin`? I don't know anything about this.

**Comment by pexcn** [comment]
In addition, Xiaomi AX1800 and Redmi AX5 should be two similar models. Their firmware maybe can used universally.

**Comment by JiaY-shi** [comment]
> @JiaY-shi For this repo I haven't tried yet, but I have some experience with openwrt [19.07](https://github.com/openwrt-dev/openwrt-ipq60xx/commits/openwrt-19.07) version (kernel 4.4.60).
> 
> For this version, except that the kernel version is too low and batman-adv cannot compile with the V protocol, everything else works well. For ZN-M2, everything works well, but after turning on wireless, the SoC temperature is 10 degrees higher than that of disabled wireless, maybe it's because ZN-M2 doesn't radiating well. For Xiaomi AX1800, everything works fine except wireless. It's wireless signal is extremely low, I think this firmware caused by the lack of `board-2.bin` for this model, but how to obtain `board-2.bin`? I don't know anything about this.

@pexcn The 4.4.60 kernel is the qsdk kernel and is too old. It is normal that some new features are not supported. This is also the reason why there is this repo.

As for the board-2.bin file, it can be extracted from the original factory firmware.

**Comment by pexcn** [comment]
> As for the board-2.bin file, it can be extracted from the original factory firmware.

@JiaY-shi I have unpacked the official firmware through binwalk.
Can you tell me how to extract it? Through what tools and in what ways?

**Comment by pexcn** [comment]
There is another question, if Xiaomi AX1800 wants to use this repo, can I use the [DTS]( https://github.com/openwrt-dev/openwrt-ipq60xx/commit/53c7d34f1f55f66f1bc8b79363512942fdbcfec4) here directly? Does it need to be rewrite?

**Comment by JiaY-shi** [comment]
@pexcn 
> > As for the board-2.bin file, it can be extracted from the original factory firmware.
> 
> @JiaY-shi I have unpacked the official firmware through binwalk. Can you tell me how to extract it? Through what tools and in what ways?

You can unzip the stock firmware and find it in the /lib/firmware directory. Or you can flash the stock firmware into the router and find it from /lib/firmware directory.


> There is another question, if Xiaomi AX1800 wants to use this repo, can I [use the DTS](https://github.com/openwrt-dev/openwrt-ipq60xx/commit/53c7d34f1f55f66f1bc8b79363512942fdbcfec4) here directly? Does it need to be rewrite?

It seems feasible, you can try it.

**Comment by pexcn** [comment]
Hello @JiaY-shi, today I tried to [add support for ZN-M2](https://github.com/openwrt-dev/openwrt-ipq60xx/commit/f78afda5d6e3cb20dac4d4e10e51b542e849e736).

I also refer to [this commit](https://github.com/coolsnowwolf/openwrt-gl-ax1800/commit/651f120), so I have a question, do I need to add [this line](https://github.com/coolsnowwolf/openwrt-gl-ax1800/blob/651f120161c70ac9ec238412dc4501ae79782b4c/target/linux/ipq60xx/image/Makefile#L65) and [this line](https://github.com/coolsnowwolf/openwrt-gl-ax1800/blob/651f120161c70ac9ec238412dc4501ae79782b4c/target/linux/ipq60xx/patches-4.4/901-arm64-boot-add-dts-files.patch#L15)?

**Comment by pexcn** [comment]
> You can unzip the stock firmware and find it in the /lib/firmware directory. Or you can flash the stock firmware into the router and find it from /lib/firmware directory.

Does it mean that it cannot be obtained through unpacking, must be flash back to the official firmware to obtain this file?
Is it generated at runtime?

Recently I also know about [a tool](https://github.com/qca/qca-swiss-army-knife)  Can it obtain `board-2.bin` from official unpacked files?

**Comment by pexcn** [comment]
> Neither line is needed.

But why not needed? How does it know that what I need is the dts file of `zn-m2`?

> It's not generated at runtime, I think it can be extracted from the original firmware, I'm a little unsure since it's been so long.
As for the tool you mentioned, it is indeed needed. You can try to use this tool to unpack [my boad-2.bin file](https://github.com/JiaY-shi/openwrt/blob/ipq60xx-devel/package/firmware/ipq-wifi/src/board-glinet_gl-ax1800.ipq6018?rgh-link-date=2023-10-26T14%3A20%3A07Z), and then combine it with [this dts file](https://github.com/JiaY-shi/openwrt/blob/dc64becf08880e79d9d66c1b701342a9e72fb081/target/linux/qualcommax/files/arch/arm64/boot/dts/qcom/ipq6018-gl-ax1800.dts#L83C4-L83C4), and you will know what you have changed.

It's a bit complicated indeed 😅, I'll try it later.

**Comment by pexcn** [comment]
Hello @JiaY-shi, I use [ath11k-bdencoder](https://github.com/qca/qca-swiss-army-knife/blob/master/tools/scripts/ath11k/ath11k-bdencoder) extracted your `board-2.bin` file, found many 64KB files.
![image](https://github.com/JiaY-shi/openwrt/assets/4590439/a2ebe0e4-0a44-4e01-ad4c-2ae1241f7e39)

At the same time, I extracted the official firmware and found that there were many 64KB files in the firmware directory.
![image](https://github.com/JiaY-shi/openwrt/assets/4590439/ad4779de-24dc-4ab8-86ef-2254c279591e)

So does this mean I can generate `board-2.bin` from these 64KB files?

**Comment by JiaY-shi** [comment]
@pexcn How is the progress of your zn-m2 transplant?

**Comment by pexcn** [comment]
> @pexcn How is the progress of your zn-m2 transplant?

ZN-M2 works fine, but I just briefly tested it. There is a problem, every time I restart the ZN-M2, the wifi mac address will change.
Now I'm trying my best to port to Xiaomi AX1800 https://github.com/openwrt-dev/openwrt-ipq60xx/commits/main

**Comment by pexcn** [comment]
> So does this mean I can generate `board-2.bin` from these 64KB files?

@JiaY-shi Can you please answer this question, Do I need to use all files starting with `bdwlan` or just one of them?

**Comment by JiaY-shi** [comment]
> > So does this mean I can generate  from these 64KB files?`board-2.bin`
> 
> @JiaY-shi Can you please answer this question, Do I need to use all files starting with or just one of them?`bdwlan`

You only need to use one, but the board-id must be 255. You can also test each bdwlan file and choose the one with the best wifi signal.

> ZN-M2 works fine, but I just briefly tested it. There is a problem, every time I restart the ZN-M2, the wifi mac address will change.

Good news, as for the mac address changing every time you restart, you can confirm whether the mac address has been written in the art partition. If not, you can generate one.

**Comment by pexcn** [comment]
> You only need to use one, but the board-id must be 255. You can also test each bdwlan file and choose the one with the best wifi signal.

OK.😄

> Good news, as for the mac address changing every time you restart, you can confirm whether the mac address has been written in the art partition. If not, you can generate one.

The art partition should exist, I'll check it out when I have time.
I also saw it is extracted to `/lib/firmware/ath11k/IPQ6018/hw1.0/cal-ahb-c000000.wifi.bin` when booting.

**Comment by pexcn** [comment]
Today I almost finished porting this firmware to Xiaomi AX1800, but there are still two small issues.
1. Wrong mac address of ethernet port, I hope it can be consistent with the mac address of the original firmware (eth0 ~ 2 as lan mac, eth3 as wan mac). What should I do?
2. It won't boot again after every reboot, need to re-plug and unplug the power supply to power on. TTL output shows it's stuck in this position:
```log
Format: Log Type - Time(microsec) - Message - Optional Info
Log Type: B - Since Boot(Power On Reset),  D - Delta,  S - Statistic
S - QC_IMAGE_VERSION_STRING=BOOT.XF.0.3-00077-IPQ60xxLZB-2
S - IMAGE_VARIANT_STRING=IPQ6018LA
S - OEM_IMAGE_VERSION_STRING=crm-ubuntu64
S - Boot Interface: NAND
S - Secure Boot: Off
S - Boot Config @ 0x000a602c = 0x000002e5
S - JTAG ID @ 0x000a607c = 0x001390e1
S - OEM ID @ 0x000a6080 = 0x00000000
S - Serial Number @ 0x000a4128 = 0x717a2e02
S - OEM Config Row 0 @ 0x000a4188 = 0x0000000000000000
S - OEM Config Row 1 @ 0x000a4190 = 0x0000000000000000
S - Feature Config Row 0 @ 0x000a4130 = 0x0000800018200021
S - Feature Config Row 1 @ 0x000a4138 = 0x02c3e83783000009
S - PBL Patch Ver: 1
S - I-cache: On
S - D-cache: On
B -      3413 - PBL, Start
B -       592 - bootable_media_detect_entry, Start
B -      4339 - bootable_media_detect_success, Start
B -      5147 - elf_loader_entry, Start
B -      5319 - auth_hash_seg_entry, Start
B -      7786 - auth_hash_seg_exit, Start
B -      8283 - elf_segs_hash_verify_entry, Start
B -    110537 - elf_segs_hash_verify_exit, Start
B -    114961 - auth_xbl_sec_hash_seg_entry, Start
B -    115103 - auth_xbl_sec_hash_seg_exit, Start
B -    121651 - xbl_sec_segs_hash_verify_entry, Start
B -    121652 - xbl_sec_segs_hash_verify_exit, Start
B -    122581 - PBL, End
B -    103364 - SBL1, Start
B -    243420 - GCC [RstStat:0x2, RstDbg:0x420100] WDog Stat : 0x4
B -    245891 - clock_init, Start
D -      2745 - clock_init, Delta
B -    254370 - boot_flash_init, Start
D -     26626 - boot_flash_init, Delta
B -    284229 - sbl1_ddr_set_default_params, Start
D -       244 - sbl1_ddr_set_default_params, Delta
B -    290848 - boot_config_data_table_init, Start
D -      4819 - boot_config_data_table_init, Delta - (575 Bytes)
B -    300760 - CDT Version:2,Platform ID:8,Major ID:3,Minor ID:2,Subtype:0
B -    305549 - Image Load, Start
D -      6588 - OEM_MISC Image Loaded, Delta - (0 Bytes)
B -    314882 - Image Load, Start
D -      5063 - PMIC Image Loaded, Delta - (0 Bytes)
B -    322751 - sbl1_ddr_set_params, Start
B -    327722 - CPR configuration: 0x366
B -    330925 - Pre_DDR_clock_init, Start
D -       213 - Pre_DDR_clock_init, Delta
D -         0 - sbl1_ddr_set_params, Delta
```

@JiaY-shi Do you have any suggestions? :)

**Comment by pexcn** [comment]
Good news🎉: the upstream appears to be adding support for IPQ60xx and IPQ50xx in the near future.
https://github.com/openwrt/openwrt/pull/12923
https://github.com/openwrt/openwrt/pull/13826

**Comment by pexcn** [comment]
UPDATE: My Xiaomi AX1800 firmware is ready to use, but 2 questions remain.
1. Won't boot again after every reboot, need to replug power supply. Please see my previous post for details.
2. WiFi upload speed is not fast enough, only half the download speed.

![image](https://github.com/JiaY-shi/openwrt/assets/4590439/bf88d08f-1be0-47bb-8323-b201eb883fa5)

@JiaY-shi Does GL-iNet AX1800 encounter the problem of slow upload speed?
