### ISSUE TITLE
额。。一个IPQ6000 CPU频率问题

### ISSUE THREAD

**Issue by Aes64X** [JiaY-shi/openwrt#20]
### Describe the bug

虽然运行起来没什么大问题，我发现CPU频率仅在800+MHz和1056MHz之间跳动，打包了MHz工具进行读取，仍然显示最高1056MHz，没有别的设定。观察补丁文件里是有opp设定的，我没找到其他原因。。。。
有什么想法？

### OpenWrt version

23.05

### OpenWrt release

23.05

### OpenWrt target/subtarget

23.05

### Device

ZN-M2

### Image kind

Self-built image

### Terms

- [X] I am reporting an issue for OpenWrt, not an unsupported fork.

**Comment by JiaY-shi** [comment]
可以调整https://github.com/JiaY-shi/openwrt/blob/ipq60xx-devel/target/linux/qualcommax/patches-6.1/0154-arm64-dts-qcom-ipq6018-use-CPUFreq-NVMEM.patch 这个补丁，把 opp-supported-hw 的值都调整成0xf，理论上ipq6000可以超到1.5GHz

**Comment by Aes64X** [comment]
> 可以调整https://github.com/JiaY-shi/openwrt/blob/ipq60xx-devel/target/linux/qualcommax/patches-6.1/0154-arm64-dts-qcom-ipq6018-use-CPUFreq-NVMEM.patch 这个补丁，把 opp-supported-hw 的值都调整成0xf，理论上ipq6000可以超到1.5GHz

多谢，改了内核dtsi解决的。不过。。。明显大佬的方法更简单。🤣🤣🤣🤣
