### ISSUE TITLE
亚瑟编译完刷进去不能启动

### ISSUE THREAD

**Issue by andyhang1980** [JiaY-shi/openwrt#25]
### Describe the bug

亚瑟编译完刷进去不能启动

### OpenWrt version

nss

### OpenWrt release

null

### OpenWrt target/subtarget

null

### Device

亚瑟

### Image kind

Self-built image

### Terms

- [X] I am reporting an issue for OpenWrt, not an unsupported fork.

**Comment by JiaY-shi** [comment]
无法复现
