### ISSUE TITLE
AX5测试6.6内核及wifi nss无问题

### ISSUE THREAD

**Issue by breeze303** [JiaY-shi/openwrt#26]
### Describe the bug

![29F927D317AC0630D8865B18A8A14D47](https://github.com/JiaY-shi/openwrt/assets/122870904/05d2abbb-48bf-4aba-b28a-26bb15bc135b)

### OpenWrt version

6.6.22

### OpenWrt release

6.6.22

### OpenWrt target/subtarget

ipq60xx

### Device

ax5

**Comment by JiaY-shi** [comment]
? 没搞明白，这个是有效还是无效？

**Comment by breeze303** [comment]
有效的，我是网线连接ax5电脑做iperf3服务端，手机连ax5的wifi做客户端，所以cpu是有占用，nss也会有占用

**Comment by JiaY-shi** [comment]
不可能的，ath11k没有集成nss支持

**Comment by JiaY-shi** [comment]
> > 不可能的，ath11k没有集成nss支持
> 
> 无线确实是没有nss支持，有线目前是能看到nss有占用，需要更多的测试

有线nss应该是ok的

**Comment by m0eak** [comment]
怎么显示nss占用的啊？

**Comment by breeze303** [comment]
修改luci
