### ISSUE TITLE
非nss分支编译完cpu调频缺少ondemand powersave模式

### ISSUE THREAD

**Issue by m0eak** [JiaY-shi/openwrt#28]
### Describe the bug

非nss分支编译完cpu调频缺少ondemand powersave模式，一样的config进行编译的 ，只调整了这两个patch
sed -i '49s/0x3/0xf/;56s/0x3/0xf/;63s/0x1/0xf/' ./target/linux/qualcommax/patches-6.6/0054-v6.8-arm64-dts-qcom-ipq6018-use-CPUFreq-NVMEM.patch

sed -i '39s/0x3/0xf/;47s/0x3/0xf/;55s/0x1/0xf/' ./target/linux/qualcommax/patches-6.6/0910-arm64-dts-qcom-ipq6018-change-voltage-to-perf-levels.patch

### OpenWrt version

23.05

### OpenWrt release

1

### OpenWrt target/subtarget

1

### Device

1

### Image kind

Self-built image

### Terms

- [X] I am reporting an issue for OpenWrt, not an unsupported fork.

**Comment by breeze303** [comment]
你这样改patch会生效？

**Comment by m0eak** [comment]
> 你这样改patch会生效？

会啊，这和手改不一样吗

**Comment by breeze303** [comment]
> > 你这样改patch会生效？
> 
> 会啊，这和手改不一样吗

不应该是make target/linux/{clean,prepare} V=s QUILT=1之后用quilt打包吗，之前试过直接手改貌似不生效不知道为啥

**Comment by breeze303** [comment]
[https://github.com/breeze303/ipq60xx-6.6/blob/main/target/linux/qualcommax/patches-6.6/0054-v6.8-arm64-dts-qcom-ipq6018-use-CPUFreq-NVMEM.patch](url)
[https://github.com/breeze303/ipq60xx-6.6/blob/main/target/linux/qualcommax/patches-6.6/0910-arm64-dts-qcom-ipq6018-change-voltage-to-perf-levels.patch](url)
你可以用这两个替换试试

**Comment by m0eak** [comment]
> [https://github.com/breeze303/ipq60xx-6.6/blob/main/target/linux/qualcommax/patches-6.6/0054-v6.8-arm64-dts-qcom-ipq6018-use-CPUFreq-NVMEM.patch](url) [https://github.com/breeze303/ipq60xx-6.6/blob/main/target/linux/qualcommax/patches-6.6/0910-arm64-dts-qcom-ipq6018-change-voltage-to-perf-levels.patch](url) 你可以用这两个替换试试

但是我编译完调频是有的，而且coremark和aes跑分也会随我设置的频率变化，就是没有ondemand和powersave只有performance和schedutil

**Comment by breeze303** [comment]
> > [https://github.com/breeze303/ipq60xx-6.6/blob/main/target/linux/qualcommax/patches-6.6/0054-v6.8-arm64-dts-qcom-ipq6018-use-CPUFreq-NVMEM.patch](url) [https://github.com/breeze303/ipq60xx-6.6/blob/main/target/linux/qualcommax/patches-6.6/0910-arm64-dts-qcom-ipq6018-change-voltage-to-perf-levels.patch](url) 你可以用这两个替换试试
> 
> 但是我编译完调频是有的，而且coremark和aes跑分也会随我设置的频率变化，就是没有ondemand和powersave只有performance和schedutil，nss分支是有的

那你可以看下这个插件相关的代码，看看是不是package缺少了什么，又或者是linux的patch不一样

**Comment by JiaY-shi** [comment]
删除这个补丁试试 0910-arm64-dts-qcom-ipq6018-change-voltage-to-perf-levels.patch

**Comment by m0eak** [comment]
好的 

 

 




 
 
  
 
  ----- 原始邮件 -----
  
发件人：shi ***@***.***>
  
***@***.***>等3人
  
主题：Re:_[JiaY-shi/openwrt]_非nss分支编译完cpu调频缺少ondemand_powersave模式_(Issue_#28)
  
日期：2024年04月14日 16:43:40
  

 
 
 
  
 删除这个补丁试试 0910-arm64-dts-qcom-ipq6018-change-voltage-to-perf-levels.patch

**Comment by m0eak** [comment]
> 删除这个补丁试试 0910-arm64-dts-qcom-ipq6018-change-voltage-to-perf-levels.patch

好像还是没有
