### ISSUE TITLE
jdc ax1800pro

### ISSUE THREAD

**Issue by czghzh** [JiaY-shi/openwrt#36]
### Describe the bug

你好，京东云ax1800pro 编译出来的主频才1200,能改成1800吗，CPU太低太卡了

### OpenWrt version

ipq60xx-devel_nss

### OpenWrt release

ipq60xx-devel_nss

### OpenWrt target/subtarget

ipq60xx-devel_nss

### Device

ipq60xx-devel_nss

### Image kind

Official downloaded image

### Terms

- [x] I am reporting an issue for OpenWrt, not an unsupported fork.

**Comment by youfun** [comment]
lz你的dockerman运行正常么。我的启动不了

**Comment by JiaY-shi** [comment]
你可以重写opp_table表，ipq6000最高支持1.5，建议保持1.2以下运行
