### ISSUE TITLE
ipq60xx-devel_nss分支dhcp无法获取上层ip，设置静态也无法上网

### ISSUE THREAD

**Issue by zlxyc** [JiaY-shi/openwrt#37]
### Describe the bug

ipq60xx-devel_nss分支,JDCloud AX1800 Pro的dhcp无法获取上层ip，设置静态也无法上网。这里是日志和编译的config

[系统日志.txt](https://github.com/JiaY-shi/openwrt/files/15345970/default.txt)

[内核日志.txt](https://github.com/JiaY-shi/openwrt/files/15345973/default.txt)

[config.txt](https://github.com/JiaY-shi/openwrt/files/15345872/config.txt)

![截图20240517162750](https://github.com/JiaY-shi/openwrt/assets/10244713/3ede84cb-d509-42ce-be05-a6fd3013cb62)

### OpenWrt version

r26351-705d7fcae5

### OpenWrt release

SNAPSHOT

### OpenWrt target/subtarget

qualcommax/ipq60xx

### Device

JDCloud AX1800 Pro

### Image kind

Self-built image

### Terms

- [ ] I am reporting an issue for OpenWrt, not an unsupported fork.

**Comment by SeamusCheng** [comment]
同样的问题，你解决了吗

**Comment by JiaY-shi** [comment]
我手头暂无设备测试，尝试在dts文件中switch节点中增加 `switch_mac_mode = <MAC_MODE_PSGMII>;` 试试呢

**Comment by DSKing377** [comment]
我也是，编译了几次都是这个问题。。。

**Comment by JiaY-shi** [comment]
请拉最新的代码重新编译试试，应该修复了，感谢 @jinfeijie 远程测试
