### ISSUE TITLE
请求添加AX5JDC设备

### ISSUE THREAD

**Issue by f1owkang** [JiaY-shi/openwrt#41]
### Describe the bug

大佬可以添加AX5JDC设备吗，我可以帮忙测试，这个仓库有设备树 https://github.com/breeze303/openwrt-6.x

### OpenWrt version

23

### OpenWrt release

23

### OpenWrt target/subtarget

23

### Device

RA50

### Image kind

Self-built image

### Terms

- [X] I am reporting an issue for OpenWrt, not an unsupported fork.

**Comment by JiaY-shi** [comment]
我手头没有的设备一般不支持，因为无法保证使用，你提到的仓库有你就直接使用他的就好了
