### ISSUE TITLE
openwrt编译ffmpeg Makefile文件中添加libx264依赖，Libraries中找不到libx264是为什么问题？lede源码可以在Libraries中选择libx264

### ISSUE THREAD

**Issue by yonggedebaqi** [JiaY-shi/openwrt#42]
### Describe the bug

openwrt编译ffmpeg Makefile文件中添加libx264依赖，Libraries中找不到libx264是为什么问题？lede源码可以在Libraries中选择libx264

### OpenWrt version

无

### OpenWrt release

无

### OpenWrt target/subtarget

无

### Device

ipq60xx-jdc_ax1800-pro

### Image kind

Official downloaded image

### Terms

- [X] I am reporting an issue for OpenWrt, not an unsupported fork.

**Comment by JiaY-shi** [comment]
与设备无关，请去openwrt官方询问

**Comment by yonggedebaqi** [comment]
谢谢你！！~解决了
make menuconfig
进入
Global build settings  --->
选中
[*] Compile with support for patented functionality 

在
Libraries  --->
就可以选择libx264 libx265了
<*> libx264...................................... H264/AVC free codec library 
<*> libx265..................................... H265/HEVC free codec library
