### ISSUE TITLE
FullConeNAT 是否有效？

### ISSUE THREAD

**Issue by pexcn** [JiaY-shi/openwrt#46]
想问一下 https://github.com/JiaY-shi/openwrt/commit/363bdc2782100454c1d26043e49abdac8ed1c4f7 提交的 FullConeNAT 是否有效？

我尝试过类似的提交，使用主分支没有效果，而在openwrt-21.05分支上有效。

**Comment by JiaY-shi** [comment]
我在主路由GL-MT6000上有效的，GL-AX1800/GL-AXT1800上没有验证过

**Comment by pexcn** [comment]
请问用的是 [fullconenat](https://github.com/JiaY-shi/openwrt/commit/363bdc2782100454c1d26043e49abdac8ed1c4f7) 还是 [nft-fullcone](https://github.com/JiaY-shi/openwrt/commit/7167826c538067955554f1b70453336149ecd5b1) 呢？

**Comment by pexcn** [comment]
用 nft-fullcone 可以
